export const GET_ALL_VACCINES = "GET_ALL_VACCINES";
export const GET_ALL_VACCINES_PENDING = "GET_ALL_VACCINES_PENDING";
export const GET_ALL_VACCINES_FULFILLED = "GET_ALL_VACCINES_FULFILLED";
export const GET_ALL_VACCINES_REJECTED = "GET_ALL_VACCINES_REJECTED";
